// js/shopDetailsData.js
// Data arrays for the Shop Details Generator.

const SHOP_LOCATIONS = [
  "shop",
  "house",
  "market stall",
  "workshop",
  "laboratory",
  "smithy",
  "mansion",
  "inn",
  "tavern",
  "temple",
  "tower",
  "castle",
  "garden",
  "ship",
  "cave",
  "carriage",
  "hut",
  "treehouse",
  "gallery",
  "ruins",
  "basement",
  "attic",
  "alley stall",
  "canal barge",
  "city gate kiosk",
  "bridge booth",
  "roadside stand",
  "old windmill",
  "abandoned chapel",
  "converted barn",
  "mine entrance",
  "watchtower",
  "lighthouse",
  "dockside warehouse",
  "floating raft shop",
  "sewer hideout",
  "graveyard crypt",
  "cliffside ledge shop",
  "giant mushroom hut",
  "wagon caravan",
];

const SHOP_APPEARANCES = [
  "cluttered and messy",
  "minimalistic and organized",
  "dark and damp",
  "bright and colorful",
  "decrepit and dusty",
  "small and cozy",
  "beautiful and well-decorated",
  "large and spacious",
  "cramped and overfilled with shelves",
  "dimly lit by flickering candles",
  "lit by softly glowing crystals",
  "warm and firelit",
  "cold and drafty",
  "smoky from constant fires",
  "heavy with incense",
  "strangely spotless",
  "covered in strange runes",
  "lined with dusty tomes",
  "hung with drying herbs",
  "crowded with hanging trinkets",
  "echoing and cavernous",
  "filled with ticking mechanisms",
  "stacked with crates and barrels",
  "decorated with animal trophies",
  "perfumed with exotic scents",
  "humid and overgrown with plants",
  "glittering with polished metal",
  "lit by colorful lanterns",
  "shadowy and full of corners",
];

const SHOP_QUIRKS = [
  "smells like rotten eggs",
  "smells like fresh baking",
  "invisible servants stock the shelves",
  "unnaturally warm",
  "uncomfortably cold",
  "an exotic pet growls at bad offers",
  "a clockwork toy claps at good offers",
  "a parrot repeats the merchant's offers",
  "ambient noise is dampened",
  "the air is as humid as a jungle",
  "candles burn with green flames",
  "a faint magical humming fills the air",
  "dust rearranges itself when no one is looking",
  "items occasionally float slightly above their shelves",
  "a magical bell rings whenever someone lies",
  "a cat judges customers from the counter",
  "the floorboards whisper when stepped on",
  "shadows move slightly out of sync",
  "a faint breeze blows despite closed doors",
  "every surface is slightly sticky",
  "customers feel slightly watched",
  "the shop smells faintly of ozone",
  "a magical broom sweeps constantly",
  "an unseen choir hums softly",
  "prices on a chalkboard change themselves",
  "books flutter open by themselves",
  "the door creaks like it is complaining",
  "customers hear distant thunder indoors",
  "tiny glowing motes drift in the air",
  "whispers echo from the rafters",
  "a skull on the counter answers simple questions",
  "a crystal ball slowly rotates on its own",
  "mirrors occasionally fog over",
  "the shelves rearrange overnight",
  "an unseen creature snores somewhere",
  "the shop smells strongly of herbs",
  "wind chimes ring even without wind",
  "customers occasionally hear faint laughter",
  "a magical lantern changes colors",
  "the floor slopes slightly toward the counter",
  "customers briefly feel weightless",
  "the door opens only after a polite knock",
  "strange runes glow faintly on the walls",
  "a stuffed animal occasionally turns its head",
  "a raven watches customers silently",
  "the ceiling is painted with moving stars",
  "the shop smells like sea salt",
  "customers feel mildly sleepy inside",
  "the shop smells strongly of sulfur",
  "a tiny elemental warms the room",
  "a tiny elemental cools the room",
  "coins occasionally rattle on the counter",
  "a bell rings randomly for no reason",
  "customers feel static electricity in the air",
  "tiny illusions drift between shelves",
  "items glow faintly in the dark",
  "the shop smells faintly of lavender",
  "every whisper echoes loudly",
  "customers hear distant chanting",
  "a magical hourglass slowly turns itself",
  "the lights dim whenever someone bargains",
  "the smell changes depending on the weather",
  "a tiny dragon statue occasionally exhales smoke",
  "the door locks itself at sunset",
  "a magical quill writes down purchases",
  "a broom follows customers around",
  "a jar of glowing insects lights the room",
  "customers swear the shop looks larger inside",
  "tiny footprints appear in dust overnight",
  "a stuffed monster head occasionally growls",
  "the floor creaks in a rhythm like breathing",
  "a magical globe shows the weather outside",
  "every purchase is followed by a tiny spark",
  "a phantom bell announces closing time",
  "customers hear distant ocean waves",
  "a magical cat statue blinks occasionally",
  "the walls are warm to the touch",
  "a faint scent of cinnamon lingers",
  "tiny sparks dance across metal objects",
  "customers occasionally see fleeting ghosts",
  "the shop smells like wet stone",
  "the counter always feels slightly warm",
  "a clock runs backwards",
  "the door handle shocks people slightly",
  "customers hear faint music with no source",
  "a magical portrait watches customers",
  "the shop always feels twilight-dark",
  "tiny bells jingle when magic is used",
  "the air smells like rain",
  "customers feel slightly taller inside",
  "a ghost cat naps on the shelves",
  "candles relight themselves when blown out",
  "the shop smells like burning wood",
  "the floor briefly trembles occasionally",
  "customers hear distant hammering",
  "the shop smells strongly of ink",
  "customers feel mildly enchanted",
  "tiny sparks dance across potion bottles",
  "a magical lantern follows customers",
  "customers occasionally see illusions in mirrors",
  "the walls whisper old gossip",
  "customers feel like time slows slightly",
  "the shop smells like old parchment",
  "a ghostly broom dusts invisible shelves",
  "tiny illusions of coins float in jars",
  "the shop smells faintly metallic",
  "a magical map shifts on the wall",
  "customers hear faint animal sounds",
  "the air tastes faintly sweet",
  "the shop smells faintly of brimstone",
  "customers feel briefly nostalgic",
  "the shop smells like damp moss",
];

const SHOP_SECURITY = [
  "items on display are illusions",
  "items are cursed until paid for",
  "items are kept in an extradimensional space",
  "items make loud noises when moved",
  "items are destroyed if merchant dies",
  "an antimagic field prevents spellcasting",
  "mercenaries are sent to catch thieves",
  "the shop is protected by guardians (DM choice)",
  "a magical alarm triggers if items leave the shop unpaid",
  "the door locks itself during suspicious activity",
  "runes flare when someone attempts theft",
  "a glyph of warding detonates on stolen goods",
  "invisible stalkers watch the shelves",
  "animated armor patrols the shop",
  "a shield guardian stands silently in the corner",
  "a mimic disguises itself as a treasure chest",
  "a mimic disguises itself as a shelf",
  "the floor becomes sticky when theft is detected",
  "the walls grow grasping vines if someone steals",
  "a magical eye follows customers",
  "an arcane mark brands thieves",
  "teleportation is blocked inside the shop",
  "a teleport trap returns stolen goods to the counter",
  "illusory duplicates confuse would-be thieves",
  "items teleport back to the shelf if stolen",
  "items scream for help when stolen",
  "items shock anyone who tries to pocket them",
  "a magical bell rings across the street when theft occurs",
  "the merchant can magically track every item sold",
  "a bound spirit watches the shop",
  "ghostly hands grab fleeing thieves",
  "an invisible barrier seals the door if theft occurs",
  "the merchant can freeze customers in place with a command word",
  "a rune marks anyone who attempts theft",
  "magical chains bind thieves instantly",
  "a magical net falls from the ceiling",
  "arcane sigils prevent pockets from holding stolen items",
  "the shopkeeper can see through every mirror in the shop",
  "the shelves animate and block exits",
  "items turn to smoke if stolen",
  "a magical ledger records every item touched",
  "the shop temporarily traps thieves in a pocket dimension",
  "a gargoyle statue awakens if theft occurs",
  "stone golems guard the storeroom",
  "clockwork guards patrol the aisles",
  "arcane turrets fire stunning bolts",
  "a magical fog disorients thieves",
  "an illusion maze traps escaping thieves",
  "the door teleports fleeing thieves back inside",
  "a magic mouth loudly accuses thieves",
  "arcane shackles appear on thieves' wrists",
  "items become unbearably hot if stolen",
  "items become unbearably cold if stolen",
  "a curse causes stolen goods to scream constantly",
  "stolen items attract monsters",
  "the shop floor collapses into a holding pit",
  "a hidden crossbow turret fires warning shots",
  "the merchant has a sending stone to call guards",
  "a trained griffon patrols the rooftop",
  "a trained blink dog guards the storeroom",
  "a trained pseudodragon alerts the merchant",
  "trained ravens watch for theft",
  "the shop cat is secretly a polymorphed wizard",
  "the shop dog is actually a celestial guardian",
  "the merchant secretly casts detect thoughts",
  "the merchant secretly casts zone of truth during sales",
  "the merchant secretly casts detect magic on customers",
  "customers are subtly marked with magical dust",
  "the door demands a password after dark",
  "the door only opens for honest customers",
  "runes prevent concealed weapons",
  "a hidden trapdoor drops thieves into the cellar",
  "the ceiling releases sleeping gas",
  "illusionary guards patrol the aisles",
  "an unseen servant quietly reports suspicious behavior",
  "the counter contains a hidden wand of hold person",
  "the shopkeeper wears a ring of spell storing",
  "a bound devil hunts down thieves",
  "a bound elemental guards the vault",
  "the vault can only be opened with a riddle",
  "the vault opens only for the merchant's voice",
  "a magical statue identifies thieves",
  "arcane light reveals invisible creatures",
  "the floor reveals hidden footprints",
  "a magical seal prevents leaving with unpaid goods",
  "a hidden glyph paralyzes thieves",
  "a magical chain drags stolen goods back to the shelf",
  "the shop briefly freezes time if theft occurs",
  "a magical horn alerts nearby guards",
  "the door grows iron bars during theft",
  "the shopkeeper can summon city guards magically",
  "an invisible barrier surrounds valuable displays",
  "items vanish if someone runs toward the door",
  "a magical tattoo appears on thieves' foreheads",
  "a rune teleports thieves to the town jail",
  "a magic circle traps fiends and undead thieves",
  "an enchanted mirror reveals criminals",
  "the shopkeeper can magically seal the entire building",
  "the shopkeeper keeps a hidden wand of lightning bolt",
  "an enchanted chandelier drops a net on thieves",
  "the merchant secretly keeps a scroll of banishment",
  "a hidden lever releases trained guard dogs",
  "a magical voice loudly shames thieves",
  "the shopkeeper is secretly a retired adventurer",
  "the shopkeeper has a silent alarm to the local thieves guild",
  "a magical cage forms around the exit",
  "a stone statue grapples fleeing thieves",
  "a magical contract binds anyone who enters",
  "anyone caught stealing cannot speak lies afterward",
  "anyone caught stealing cannot leave town for a day",
  "anyone caught stealing glows bright purple",
];